import 'server-only'

import { ObjectId, type Collection } from 'mongodb'
import { randomUUID } from 'node:crypto'
import { getDb } from './mongodb'

/** How a rent payment reached us: an automatic Stripe charge or recorded cash. */
export type EquitySource = 'stripe' | 'cash'

/**
 * Rent-accrued equity ledger. One row per successful rent payment: an admin-set,
 * property-specific percentage of the rent is credited to the partner as equity.
 * The Stripe webhook writes these; partner cards/reports and payouts read them.
 */
export interface RentEquityDoc {
  _id: ObjectId
  partnerId: ObjectId
  propertyId: ObjectId
  tenantId: ObjectId
  /**
   * Unique payment reference — the Stripe invoice id for auto charges, or a
   * generated `cash_…` ref for manually-recorded cash. Unique, so repeated
   * webhook delivery (or a double form submit) can't double-credit.
   */
  stripeInvoiceId: string
  /** Whether this came from Stripe or was recorded as a cash payment. */
  source: EquitySource
  /** Rent actually charged/received, in cents (the share basis). */
  rentCents: number
  /** Percentage of rent credited to the partner. */
  sharePercent: number
  /** Equity credited to the partner for this payment, in cents. */
  equityCents: number
  paidAt: Date
}

export type RentEquityEntry = {
  id: string
  propertyId: string
  source: EquitySource
  rentCents: number
  sharePercent: number
  equityCents: number
  paidAt: Date
}

async function equityCollection(): Promise<Collection<RentEquityDoc>> {
  const db = await getDb()
  const col = db.collection<RentEquityDoc>('rentEquity')
  await col.createIndex({ stripeInvoiceId: 1 }, { unique: true })
  await col.createIndex({ partnerId: 1 })
  await col.createIndex({ propertyId: 1, paidAt: -1 })
  return col
}

function toEntry(d: RentEquityDoc): RentEquityEntry {
  return {
    id: d._id.toString(),
    propertyId: d.propertyId.toString(),
    source: d.source ?? 'stripe',
    rentCents: d.rentCents,
    sharePercent: d.sharePercent,
    equityCents: d.equityCents,
    paidAt: d.paidAt,
  }
}

/**
 * Record an equity credit for a paid rent invoice. Idempotent on the invoice id —
 * a duplicate webhook delivery is silently ignored.
 */
export async function recordRentEquity(input: {
  partnerId: string
  propertyId: string
  tenantId: string
  /** Stripe invoice id for auto charges; omit for cash (a `cash_…` ref is generated). */
  stripeInvoiceId?: string
  source?: EquitySource
  rentCents: number
  sharePercent: number
  equityCents: number
  paidAt: Date
}): Promise<void> {
  if (!ObjectId.isValid(input.partnerId) || !ObjectId.isValid(input.propertyId) || !ObjectId.isValid(input.tenantId)) {
    return
  }
  const source = input.source ?? 'stripe'
  const ref = input.stripeInvoiceId ?? `cash_${randomUUID()}`
  const col = await equityCollection()
  try {
    await col.insertOne({
      _id: new ObjectId(),
      partnerId: new ObjectId(input.partnerId),
      propertyId: new ObjectId(input.propertyId),
      tenantId: new ObjectId(input.tenantId),
      stripeInvoiceId: ref,
      source,
      rentCents: input.rentCents,
      sharePercent: input.sharePercent,
      equityCents: input.equityCents,
      paidAt: input.paidAt,
    })
  } catch (err) {
    // Duplicate invoice id (already recorded) — safe to ignore; rethrow anything else.
    if (!(err && typeof err === 'object' && 'code' in err && (err as { code?: number }).code === 11000)) {
      throw err
    }
  }
}

async function sumEquity(match: Record<string, unknown>): Promise<number> {
  const col = await equityCollection()
  const rows = await col
    .aggregate<{ total: number }>([{ $match: match }, { $group: { _id: null, total: { $sum: '$equityCents' } } }])
    .toArray()
  return rows[0]?.total ?? 0
}

/** Lifetime equity (cents) credited to a partner across all their properties. */
export async function totalEquityCentsByPartner(partnerId: string): Promise<number> {
  if (!ObjectId.isValid(partnerId)) return 0
  return sumEquity({ partnerId: new ObjectId(partnerId) })
}

/** Equity (cents) generated by one property, optionally since a date floor (e.g. YTD). */
export async function equityCentsByProperty(propertyId: string, since?: Date): Promise<number> {
  if (!ObjectId.isValid(propertyId)) return 0
  const match: Record<string, unknown> = { propertyId: new ObjectId(propertyId) }
  if (since) match.paidAt = { $gte: since }
  return sumEquity(match)
}

/**
 * Re-price every equity entry for a property to a new share percentage. Used when
 * an admin changes a property's equity share so the new rate applies immediately to
 * all accrued equity (and therefore the partner's unsent/available balance), not
 * just to future payments. Each entry's `equityCents` is recomputed from its
 * recorded `rentCents`.
 */
export async function repricePropertyEquity(propertyId: string, sharePercent: number): Promise<void> {
  if (!ObjectId.isValid(propertyId)) return
  const col = await equityCollection()
  await col.updateMany({ propertyId: new ObjectId(propertyId) }, [
    {
      $set: {
        sharePercent,
        equityCents: { $round: [{ $divide: [{ $multiply: ['$rentCents', sharePercent] }, 100] }, 0] },
      },
    },
  ])
}

/** Equity ledger entries for one property, newest first (report + email). */
export async function listEquityEntriesByProperty(propertyId: string): Promise<RentEquityEntry[]> {
  if (!ObjectId.isValid(propertyId)) return []
  const col = await equityCollection()
  const docs = await col.find({ propertyId: new ObjectId(propertyId) }).sort({ paidAt: -1 }).toArray()
  return docs.map(toEntry)
}
