import 'server-only'

import { ObjectId, type Collection } from 'mongodb'
import { getDb } from './mongodb'

/**
 * Rent-accrued equity ledger. One row per successful rent payment: an admin-set,
 * property-specific percentage of the rent is credited to the partner as equity.
 * The Stripe webhook writes these; partner cards/reports and payouts read them.
 */
export interface RentEquityDoc {
  _id: ObjectId
  partnerId: ObjectId
  propertyId: ObjectId
  tenantId: ObjectId
  /** Stripe invoice id — unique, so repeated webhook delivery can't double-credit. */
  stripeInvoiceId: string
  /** Rent actually charged on the invoice, in cents (the share basis). */
  rentCents: number
  /** Percentage of rent credited to the partner. */
  sharePercent: number
  /** Equity credited to the partner for this payment, in cents. */
  equityCents: number
  paidAt: Date
}

export type RentEquityEntry = {
  id: string
  propertyId: string
  rentCents: number
  sharePercent: number
  equityCents: number
  paidAt: Date
}

async function equityCollection(): Promise<Collection<RentEquityDoc>> {
  const db = await getDb()
  const col = db.collection<RentEquityDoc>('rentEquity')
  await col.createIndex({ stripeInvoiceId: 1 }, { unique: true })
  await col.createIndex({ partnerId: 1 })
  await col.createIndex({ propertyId: 1, paidAt: -1 })
  return col
}

function toEntry(d: RentEquityDoc): RentEquityEntry {
  return {
    id: d._id.toString(),
    propertyId: d.propertyId.toString(),
    rentCents: d.rentCents,
    sharePercent: d.sharePercent,
    equityCents: d.equityCents,
    paidAt: d.paidAt,
  }
}

/**
 * Record an equity credit for a paid rent invoice. Idempotent on the invoice id —
 * a duplicate webhook delivery is silently ignored.
 */
export async function recordRentEquity(input: {
  partnerId: string
  propertyId: string
  tenantId: string
  stripeInvoiceId: string
  rentCents: number
  sharePercent: number
  equityCents: number
  paidAt: Date
}): Promise<void> {
  if (!ObjectId.isValid(input.partnerId) || !ObjectId.isValid(input.propertyId) || !ObjectId.isValid(input.tenantId)) {
    return
  }
  const col = await equityCollection()
  try {
    await col.insertOne({
      _id: new ObjectId(),
      partnerId: new ObjectId(input.partnerId),
      propertyId: new ObjectId(input.propertyId),
      tenantId: new ObjectId(input.tenantId),
      stripeInvoiceId: input.stripeInvoiceId,
      rentCents: input.rentCents,
      sharePercent: input.sharePercent,
      equityCents: input.equityCents,
      paidAt: input.paidAt,
    })
  } catch (err) {
    // Duplicate invoice id (already recorded) — safe to ignore; rethrow anything else.
    if (!(err && typeof err === 'object' && 'code' in err && (err as { code?: number }).code === 11000)) {
      throw err
    }
  }
}

async function sumEquity(match: Record<string, unknown>): Promise<number> {
  const col = await equityCollection()
  const rows = await col
    .aggregate<{ total: number }>([{ $match: match }, { $group: { _id: null, total: { $sum: '$equityCents' } } }])
    .toArray()
  return rows[0]?.total ?? 0
}

/** Lifetime equity (cents) credited to a partner across all their properties. */
export async function totalEquityCentsByPartner(partnerId: string): Promise<number> {
  if (!ObjectId.isValid(partnerId)) return 0
  return sumEquity({ partnerId: new ObjectId(partnerId) })
}

/** Equity (cents) generated by one property, optionally since a date floor (e.g. YTD). */
export async function equityCentsByProperty(propertyId: string, since?: Date): Promise<number> {
  if (!ObjectId.isValid(propertyId)) return 0
  const match: Record<string, unknown> = { propertyId: new ObjectId(propertyId) }
  if (since) match.paidAt = { $gte: since }
  return sumEquity(match)
}

/** Equity ledger entries for one property, newest first (report + email). */
export async function listEquityEntriesByProperty(propertyId: string): Promise<RentEquityEntry[]> {
  if (!ObjectId.isValid(propertyId)) return []
  const col = await equityCollection()
  const docs = await col.find({ propertyId: new ObjectId(propertyId) }).sort({ paidAt: -1 }).toArray()
  return docs.map(toEntry)
}
